### ISSUE TITLE
issue with release v1.3.0

### ISSUE THREAD

**Issue by mehimanshupatil** [Lazyuki/rollup-plugin-rename-node-modules#6]
after updating from v1.2.0 to v1.3.0 the imports in root file were changed from "./external/**" to "external/**" 
This is causing problem in projects where the application is imported.

**Comment by Lazyuki** [comment]
The fix should be available in `v1.3.1` now. Let me know if that fixes it

**Comment by mehimanshupatil** [comment]
saw your commit 
```
const newRelativePath = newPath.startsWith("./") ? newPath : `./${newPath}`;
```
should be instead
```
const newRelativePath = newPath.startsWith(".") ? newPath : `./${newPath}`;
```

**Comment by mehimanshupatil** [comment]
any way both are correct since node is able resolve path
