### ISSUE TITLE
Update peer dependency to Rollup v3

### ISSUE THREAD

**Issue by jasonfry** [Lazyuki/rollup-plugin-rename-node-modules#8]
Hi, are there any plans to update this package to have a peer dependency of Rollup v3?

**Comment by bigtimebuddy** [comment]
Hello @Lazyuki would it be possible for you to publish a new version for v3 and we need this on several projects. Thank you!

**Comment by jasonfry** [comment]
For anyone still waiting, you can remove this package and use `entryFileNames` with rollup v3: https://github.com/rollup/rollup/issues/3684#issuecomment-1535836196

**Comment by rejhgadellaa** [comment]
It may also be worth checking if you really need `preserveModules`:

> If you want to convert a set of files to another format while maintaining the file structure and export signatures, the recommended way—instead of using `output.preserveModules` that may tree-shake exports as well as emit virtual files created by plugins—is to turn every file into an entry point. [ ...]
> Source: [Rollup - Configuration Options - Input](https://rollupjs.org/configuration-options/#input)

```javascript
import glob from 'glob';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

export default {
	input: Object.fromEntries(
		glob.sync('src/**/*.js').map(file => [
			// This remove `src/` as well as the file extension from each
			// file, so e.g. src/nested/foo.js becomes nested/foo
			path.relative(
				'src',
				file.slice(0, file.length - path.extname(file).length)
			),
			// This expands the relative paths to absolute paths, so e.g.
			// src/nested/foo becomes /project/src/nested/foo.js
			fileURLToPath(new URL(file, import.meta.url))
		])
	),
	output: {
		format: 'es',
		dir: 'dist'
	}
};
```
